---
title: "coventine o."
output: 
  html_document:
   includes:
      before_body: header.html
      after_body: footer.html
css: "vanilla.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# About

BS Psychology graduate from UCI with an interest in the intersection of psychology and human-computer interaction. I graduated with honors from the Campuswide Honors Collegium and am a proud transfer student from Los Angeles Pierce Community College. Currently centered in California.

I was also a proud member of the Neon Anteater Renaissance during my time at UCI. I contributed art, writing, and did graphic design for advertising posters.

My research interests include: equity in video games, ethics, telehealth, informatics, generational trauma, and media studies.

When I am not working, I enjoy drawing, painting, writing, violin, hiking, writing HTML websites about my interests, and playing video games!

## Research

* Sexism, Streamers, and Simulated Avatars, 2023 ([pdf]("file/chc_thesis.pdf")) - My undergraduate thesis submitted for the Campuswide Honors Collegium at UCI. A meta-analysis of literature on livestreaming, toxicity in online gaming spaces, and the use of virtual avatars in streaming -- colloquially known as "VTubing".
  * Presented in [poster format](file/urop_vtuber.png) at the UCI Undergraduate Research Symposium in 2023.
* Technology Dependency and Impulse Control, 2020 - Undergraduate group research for Psychology 74. Used a survey administered via SurveyMonkey and then analyzed with SPSS.
  * Presented in [poster format](file/tech-and-impulse.png) at Los Angeles Pierce College Research Showcase via Zoom.
* Separation and Families of Overseas Filipino Workers, 2019 - Undergraduate individual research project on the effects of early separation and families of OFWs. Concentrated on parents and children.

## Contact

**email** [cjong1227 @ gmail.com](mailto:cjong1227@gmail.com)

**resume** [pdf](file/cjong_plainresume.pdf) || [web](file/pagedownresume.html)

