---
title: "coventine o. | 'leap day'"
output: 
  html_document:
   includes:
      before_body: "header.html"
      after_body: "../footer.html"
css: "../vanilla.css"
date: "Created February 29, 2024<br>Last edited on `r format(Sys.time(), '%B %d, %Y')`"
---

# Leap Day & RMarkdown for Site Management

It's leap day so I guess I wanted to write up something small for it? It only comes around once every 4 years, so I'm not sure why we don't celebrate it more!

I've given the site a bit of a facelift since as much as I liked my last style, I need to work on my CSS skills some more until I get it figured out. I was also thinking of using a proper static site generator for this facelift, but...I ended up turning to a tool I'm already adequately familiar with: RStudio.

I used RStudio a lot in my undergrad and while there's still a lot I need to learn, RMarkdown as an own SSG is pretty useful and versatile and most importantly: not intimidating for me since I use Markdown basically every day. Admittedly it took a lot of googling for me to understand the YAML parameters -- I really need to take notes about how to write a good YAML header. At least I managed to get a functional header and footer working? Special thanks to [Holtz](https://holtzy.github.io/Pimp-my-rmd/#text_formating) for this quick and easy tutorial on RMD to HTML and injecting HTML snippets into my site.

For CSS, I'm using vanilla CSS, which is a very cool [open-source](https://vanillacss.com/) style sheet that I really liked the look of. Though I did adjust some of the colors to give my site more flavor.

I also updated the [gallery](../creative.html) to be more aesthetically pleasing too. I love Roy Francis' [pixture](https://github.com/royfrancis/pixture) library which made organizing and adding things to my gallery so much easier, though I need to figure out how to add captions if that's even possible. If I take enough pictures on my trip next month, I'll use this when I make a post about it.

Everything else started out as plain Rmd files that I outputted into HTML, but there's a billion tutorials for this online, so I'll leave you to find that out for yourself.